name: pyxdsm

on:
  push:
    branches: [main]
    tags:
      - v*.*.*
  pull_request:
    branches: [main]

jobs:
  black:
    uses: mdolab/.github/.github/workflows/black.yaml@main

  flake8:
    uses: mdolab/.github/.github/workflows/flake8.yaml@main

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]
        numpy-version: ["~=1.21.0", "~=1.26.0"]
        exclude:
        - python-version: 3.11
          numpy-version: "~=1.21.0"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install texlive-pictures texlive-latex-extra -y
          pip install -U pip wheel
          pip install testflo numpy${{ matrix.numpy-version }}
          pip install .
      - name: Test examples
        run: |
          testflo . -v

  # --- publish to PyPI
  pypi:
    needs: [test, flake8, black]
    uses: mdolab/.github/.github/workflows/pypi.yaml@main
    secrets: inherit
